const wordsData = {
  '1/7': [
    {
      id: 1,
      chinese: '苹果',
      english: 'apple',
      problem: 'appl_',
      options: { A: 'e', B: 'a' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.7-1-apple.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185112.mp3',
    },
    {
      id: 2,
      chinese: '美术',
      english: 'art',
      problem: 'ar_',
      options: { A: 'p', B: 't' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.7-2-art.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185113.mp3',
    },
    {
      id: 3,
      chinese: '坏的',
      english: 'bad',
      problem: 'ba_',
      options: { A: 'p', B: 'd' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.7-3-bad-tz.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185114.mp3',
    },
  ],
  '1/8': [
    {
      id: 1,
      chinese: '香蕉',
      english: 'banana',
      problem: 'banan_',
      options: { A: 'a', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.8-1-banana.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185115.mp3',
    },
    {
      id: 2,
      chinese: '自行车',
      english: 'bike',
      problem: 'b_ke',
      options: { A: 'i', B: 'b' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.8-2-bike.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185116.mp3',
    },
    {
      id: 3,
      chinese: '小船',
      english: 'boat',
      problem: 'bo_t',
      options: { A: 'a', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.8-2-boat-z.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185117.mp3',
    },
  ],
  '1/9': [
    {
      id: 1,
      chinese: '蛋糕',
      english: 'cake',
      problem: 'cak_',
      options: { A: 't', B: 'e' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.9-1-cake.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185118.mp3',
    },
    {
      id: 2,
      chinese: '可爱的',
      english: 'cute',
      problem: 'c_te',
      options: { A: 'e', B: 'u' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.9-2-cute.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185119.mp3',
    },
    {
      id: 3,
      chinese: '跳舞',
      english: 'dance',
      problem: 'd_nce',
      options: { A: 'a', B: 'd' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.9-3-dance-tz.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185120.mp3',
    },
  ],
  '1/10': [
    {
      id: 1,
      chinese: '画画',
      english: 'draw',
      problem: 'dr_w',
      options: { A: 't', B: 'a' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.10-1-draw-tz.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185121.mp3',
    },
    {
      id: 2,
      chinese: '吃',
      english: 'eat',
      problem: 'ea_',
      options: { A: 'a', B: 't' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.10-2-eat-z.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185122.mp3',
    },
    {
      id: 3,
      chinese: '鸡蛋',
      english: 'eggs',
      problem: '_ggs',
      options: { A: 'e', B: 'a' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.10-3-eggs.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185123.mp3',
    },
  ],
  '1/11': [
    {
      id: 1,
      chinese: '风扇',
      english: 'fan',
      problem: 'f_n',
      options: { A: 'a', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.11-1-fan.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185124.mp3',
    },
    {
      id: 2,
      chinese: '农场',
      english: 'farm',
      problem: 'fa_m',
      options: { A: 't', B: 'r' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.11-2-farm.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185125.mp3',
    },
    {
      id: 3,
      chinese: '五',
      english: 'five',
      problem: 'f_ve',
      options: { A: 'i', B: 'u' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.11-3-five.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185126.mp3',
    },
  ],
  '1/12': [
    {
      id: 1,
      chinese: '鱼，钓鱼',
      english: 'fish',
      problem: 'f_sh',
      options: { A: 'i', B: 'e' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.12-1-fish.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185127.mp3',
    },
    {
      id: 2,
      chinese: '飞',
      english: 'fly',
      problem: 'fl_',
      options: { A: 't', B: 'y' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.12-2-fly.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185128.mp3',
    },
    {
      id: 3,
      chinese: '游戏',
      english: 'game',
      problem: 'g_me',
      options: { A: 'e', B: 'a' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.12-3-game.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185129.mp3',
    },
  ],
  '1/13': [
    {
      id: 1,
      chinese: '好的',
      english: 'good',
      problem: 'goo_',
      options: { A: 'g', B: 'd' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.13-1-good-tz.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185130.mp3',
    },
    {
      id: 2,
      chinese: '讨厌',
      english: 'hate',
      problem: 'h_te',
      options: { A: 'a', B: 'e' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.13-2-hate.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185131.mp3',
    },
    {
      id: 3,
      chinese: '开心的',
      english: 'happy',
      problem: 'h_ppy',
      options: { A: 'a', B: 'e' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.13-3-happy.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185132.mp3',
    },
  ],
  '1/14': [
    {
      id: 1,
      chinese: '蜂蜜',
      english: 'honey',
      problem: 'hon_y',
      options: { A: 'e', B: 'a' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.14-1-honey.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185133.mp3',
    },
    {
      id: 2,
      chinese: '热的',
      english: 'hot',
      problem: 'h_t',
      options: { A: 'e', B: 'o' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.14-2-hot.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185134.mp3',
    },
    {
      id: 3,
      chinese: '跳',
      english: 'jump',
      problem: 'jum_',
      options: { A: 't', B: 'p' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.14-3-jump.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185135.mp3',
    },
  ],
  '1/15': [
    {
      id: 1,
      chinese: '小孩',
      english: 'kid',
      problem: 'ki_',
      options: { A: 'd', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.15-1-kid.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185137.mp3',
    },
    {
      id: 2,
      chinese: '迟的',
      english: 'late',
      problem: 'l_te',
      options: { A: 'a', B: 'p' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.15-2-late.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185138.mp3',
    },
    {
      id: 3,
      chinese: '线',
      english: 'line',
      problem: 'l_ne',
      options: { A: 'i', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.15-3-line.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185139.mp3',
    },
  ],
  '1/16': [
    {
      id: 1,
      chinese: '垫子',
      english: 'mat',
      problem: 'ma_',
      options: { A: 'r', B: 't' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.16-1-mat.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185140.mp3',
    },
    {
      id: 2,
      chinese: '数学',
      english: 'math',
      problem: 'm_th',
      options: { A: 'e', B: 'a' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.16-2-math.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185141.mp3',
    },
    {
      id: 3,
      chinese: '需要',
      english: 'need',
      problem: 'ne_d',
      options: { A: 'o', B: 'e' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.16-3-need.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185142.mp3',
    },
  ],
  '1/17': [
    {
      id: 1,
      chinese: '九',
      english: 'nine',
      problem: 'ni_e',
      options: { A: 'n', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.17-1-nine.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185143.mp3',
    },
    {
      id: 2,
      chinese: '夜晚',
      english: 'night',
      problem: 'n_ght',
      options: { A: 'i', B: 'a' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.17-2-night.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185144.mp3',
    },
    {
      id: 3,
      chinese: '锅',
      english: 'pan',
      problem: 'pa_',
      options: { A: 'n', B: 'u' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.17-3-pan.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185145.mp3',
    },
  ],
  '1/18': [
    {
      id: 1,
      chinese: '馅饼',
      english: 'pie',
      problem: 'p_e',
      options: { A: 'a', B: 'i' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.18-1-pie.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185146.mp3',
    },
    {
      id: 2,
      chinese: '玩',
      english: 'play',
      problem: 'pl_y',
      options: { A: 'a', B: 'e' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.18-2-play.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185147.mp3',
    },
    {
      id: 3,
      chinese: '壶',
      english: 'pot',
      problem: 'p_t',
      options: { A: 'n', B: 'o' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.18-3-pot.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185148.mp3',
    },
  ],
  '1/19': [
    {
      id: 1,
      chinese: '阅读',
      english: 'read',
      problem: 'rea_',
      options: { A: 'd', B: 'k' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.19-1-read.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185149.mp3',
    },
    {
      id: 2,
      chinese: '跑',
      english: 'run',
      problem: 'ru_',
      options: { A: 'n', B: 't' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.19-2-run.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185150.mp3',
    },
    {
      id: 3,
      chinese: '说',
      english: 'say',
      problem: 'sa_',
      options: { A: 'y', B: 'd' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.19-3-say.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185151.mp3',
    },
  ],
  '1/20': [
    {
      id: 1,
      chinese: '商店',
      english: 'shop',
      problem: 'sh_p',
      options: { A: 'i', B: 'o' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.20-1-shop.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185152.mp3',
    },
    {
      id: 2,
      chinese: '谈话',
      english: 'talk',
      problem: 'tal_',
      options: { A: 'y', B: 'k' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.20-2-talk.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185153.mp3',
    },
    {
      id: 3,
      chinese: '走',
      english: 'walk',
      problem: 'w_lk',
      options: { A: 'a', B: 'e' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.20-3-walk.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185154.mp3',
    },
  ],
  '1/21': [
    {
      id: 1,
      chinese: '白色的',
      english: 'white',
      problem: 'wh_te',
      options: { A: 'i', B: 'a' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.21-1-white.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185155.mp3',
    },
    {
      id: 2,
      chinese: '赢',
      english: 'win',
      problem: 'w_n',
      options: { A: 'a', B: 'i' },
      value: 'B',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.21-2-win.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185156.mp3',
    },
    {
      id: 3,
      chinese: '写',
      english: 'write',
      problem: 'wri_e',
      options: { A: 't', B: 'l' },
      value: 'A',
      imgSrc: 'https://plat-h5.cdnjtzy.com/plat/SDK/1.21-3-write.jpg',
      audioSrc: 'https://bd-s.zuoyebang.cc/zyb-185158.mp3',
    },
  ],
};
const videoDate = {
  '1/6': {
    type: '3',
    url: 'https://bd-s.zuoyebang.cc/zyb-185565.mp4',
  },
  '1/7': {
    type: '3',
    url: 'https://bd-s.zuoyebang.cc/zyb-185565.mp4',
  },
  '1/8': {
    type: '3',
    url: 'https://bd-s.zuoyebang.cc/zyb-185566.mp4',
  },
  '1/9': {
    type: '3',
    url: 'https://bd-s.zuoyebang.cc/zyb-185567.mp4',
  },
  '1/10': {
    type: '4',
    url: 'https://bd-s.zuoyebang.cc/zyb-185052.mp4',
  },
  '1/11': {
    type: '4',
    url: 'https://bd-s.zuoyebang.cc/zyb-185070.mp4',
  },
  '1/12': {
    type: '4',
    url: 'https://bd-s.zuoyebang.cc/zyb-185053.mp4',
  },
  '1/13': {
    type: '4',
    url: 'https://bd-s.zuoyebang.cc/zyb-185054.mp4',
  },
  '1/14': {
    type: '4',
    url: 'https://bd-s.zuoyebang.cc/zyb-185055.mp4',
  },
  '1/15': {
    type: '1',
    url: 'https://bd-s.zuoyebang.cc/zyb-185056.mp4',
  },
  '1/16': {
    type: '1',
    url: 'https://bd-s.zuoyebang.cc/zyb-185057.mp4',
  },
  '1/17': {
    type: '1',
    url: 'https://bd-s.zuoyebang.cc/zyb-185058.mp4',
  },
  '1/18': {
    type: '2',
    url: 'https://bd-s.zuoyebang.cc/zyb-185568.mp4',
  },
  '1/19': {
    type: '2',
    url: 'https://bd-s.zuoyebang.cc/zyb-185569.mp4',
  },
  '1/20': {
    type: '2',
    url: 'https://bd-s.zuoyebang.cc/zyb-185570.mp4',
  },
};

export { wordsData, videoDate };
